stages:
  - build
  - beta

variables:
  LC_ALL: 'en_US.UTF-8'
  LANG: 'en_US.UTF-8'

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor

build_ios:
  #image: macos-13-xcode-14
  stage: build
  script:
    - bundle check -| bundle install --jobs $(sysctl -n hw.physicalcpu)
    - bundle exec fastlane build
  tags: 
    - mus

beta_ios:
  #image: macos-13-xcode-14
  stage: beta
  script:
    - bundle check -| bundle install --jobs $(sysctl -n hw.physicalcpu)
    - bundle exec fastlane beta
  tags: 
    - mus
  when: manual
  allow_failure: true
  only:
    refs:
      - main
