stages:
  - build
  - beta

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/bundle

build_ios:
  #image: macos-13-xcode-14
  stage: build
  before_script:
    - bundle install
  script:
    - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(sysctl -n hw.physicalcpu)
    - bundle exec fastlane build
  tags: 
    - mus

beta_ios:
  #image: macos-13-xcode-14
  stage: beta
  before_script:
    - bundle install
  script:
    - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(sysctl -n hw.physicalcpu)
    - bundle exec fastlane beta
  tags: 
    - mus
  when: manual
  allow_failure: true
  only:
    refs:
      - main
